### ISSUE TITLE
Using `osConfig` to avoid installing kitty or kde in the home-manager

### ISSUE THREAD

**Issue by yzld2002** [martijnboers/nixos#1]
Hey I like your nixos config very much and actually I'm rewriting my configs based on your repo.

I like the clean separation of the os configs and home-manager configs.

One thing I noticed is that even if I set the `hosts.desktop.enable = false`, the home-manager will still install kitty or some kde components.

I see you said the `home/modules/kitty.nix` would be lazy loaded but I didn't quite understand this.
https://github.com/martijnboers/nixos/blob/f41940fefe06f6ead705bef5e3c83e119b3629f7/home/default.nix#L53-L55

To avoid installing such packages, I think using the `osConfig` provided by home-manager is a good way:

> Home Manager will pass osConfig as a module argument to any modules you create. This contains the system’s NixOS configuration.

Taking kitty as an example, I rewrite the config like the following, and the kitty won't be installed if I set the `hosts.desktop.enable = false`.
```nix
{ lib, osConfig, ... }:
with lib; let
  cfg = osConfig.hosts.desktop;
in {
  config = mkIf cfg.enable {
    programs.kitty = {
      enable = true;
...
```

I also use this `osConfig` in the `profiles/desktop.nix`.

Thank you for your great nixos config!

**Comment by noisesfromspace** [comment]
First of thank you for your interest and kind words. I only now see that I indeed have Kitty installed on non-desktop machines and I didn't know about this `osConfig` but it solves that issue. 

The lazy loading part is me thinking that if I don't have the application `kitty` all involved config wouldn't have an affect, but with the enabled true it also installs the package.
